version: '3.8'
services:
  db:
    container_name: cashforce-db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cashforce_db
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql
  backend:
    container_name: cashforce-back
    depends_on:
      - db
    build: ./cashforce-back
    environment:
      - PORT=4000
      - DB_USER=root
      - DB_HOST=db
      - DB_PASS=password
      - DB_NAME=cashforce_db
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
  frontend:
    container_name: cashforce-front
    depends_on:
      - backend
    build: ./cashforce-front
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
volumes: 
  db: